mezzanine_tools/newsletter/urls.py
from __future__ import unicode_literals

from django.conf.urls import url

from mezzanine_tools.newsletter import views as newsletter_views

app_name = "newsletter"

urlpatterns = [
    url("^register/$", newsletter_views.register, name="register"),
    url("^unregister/$", newsletter_views.unregister, name="unregister"),
    url("^activate/(?P<code>[\w-]+)/$", newsletter_views.activate, name="activate"),
]

mezzanine_tools/newsletter/models.py
from __future__ import unicode_literals

from datetime import timedelta
from uuid import uuid4

from django.core.urlresolvers import reverse
from django.db import models
from django.utils.translation import ugettext as _
from django.utils import timezone
from mezzanine.core.models import SiteRelated
from mezzanine.conf import settings


class NewsletterManager(models.Manager):

    def get_by_code(self, code):
        now = timezone.now()
        deadline = now - timedelta(days=settings.NEWSLETTER_TIMEOUT)
        print deadline
        queryset = self.filter(updated__gte=deadline).get(code=code)
        return queryset

    def get_validated(self):
        return self.filter(
            active=True,
            validated=True,
        )


class Newsletter(SiteRelated):
    email = models.EmailField(_('Email'), unique=True)
    created = models.DateTimeField(_('Created'), auto_now_add=True, editable=False)
    updated = models.DateTimeField(_('Updated'), auto_now=True, editable=False)
    active = models.BooleanField(_('Active'), default=True)
    validated = models.BooleanField(_('Validated'), default=False)
    code = models.UUIDField(_('Code'), db_index=True, unique=True, editable=False)

    objects = NewsletterManager()

    def get_new_uuid(self):
        uuid = uuid4()
        return uuid

    def get_activation_url(self):
        url = reverse("newsletter:activate", kwargs={'code': self.code.hex, })
        return url

    def save(self, *args, **kwargs):
        if not self.code:
            self.code = self.get_new_uuid()
        super(Newsletter, self).save(*args, **kwargs)

    class Meta:
        verbose_name = _('Newsletter')
        verbose_name_plural = _('Newsletter')

mezzanine_tools/newsletter/views.py
import copy
import json

from django.core.mail import send_mail
from django.http import HttpResponse, Http404
from django.shortcuts import render
from django.template import loader
from django.utils.translation import ugettext as _

from mezzanine.conf import settings

from mezzanine_tools.newsletter.models import Newsletter


def register(request):
    if request.method != 'POST':
        raise Http404()
    email = request.POST.get('email')
    newsletter, created = Newsletter.objects.get_or_create(email=email)
    if not created:
        msg = _('Email addressalready registered')
    else:
        t = loader.get_template("newsletter/email/email_confirm.txt")
        c = {
            'newsletter': newsletter
        }
        msg = t.render(context=c,)
        send_mail(
            _("Newsletter confirmaion email"),
            msg,
            settings.NEWSLETTER_FROM,
            [newsletter.email,]
        )
        msg = _('Successfully registered. We have sent you an confirmation email.')

    return render(request, 'newsletter/register.html', {'msg': msg, 'newsletter': newsletter})


def unregister(request, code):
    try:
        newsletter = Newsletter.objects.get(code=code)
        newsletter.active = False
        newsletter.save()
        msg = _('Your newsletter email address have been successfully de-registered.')
    except Newsletter.DoesNotExist:
        msg = _('Unable to de-register the newsletter email. Please contact our support.')
    return render(request, 'newsletter/unregistration_complete.html', {'msg': msg, 'newsletter': newsletter})


def activate(request, code):
    try:
        newsletter = Newsletter.objects.get_by_code(code)
        newsletter.validated = True
        newsletter.active = True
        newsletter.save()
        msg = _('Your newsletter email address have been successfully activated.')
    except Newsletter.DoesNotExist:
        msg = _('Unable to activate the newsletter email. Please contact our support.')
    return render(request, 'newsletter/registration_complete.html.html', {'msg': msg, 'newsletter': newsletter})

mezzanine_tools/newsletter/templates/newsletter/newsletter.html
<div class="shop-subscribe">
    <div class="container">
        <form id="newsletter_form" method="post" action="{% url 'newsletter:register' %}" class="row">
            <div class="col-md-8 md-margin-bottom-20">
                <h2>subscribe to our weekly <strong>newsletter</strong></h2>
            </div>
            <div class="col-md-4">
                <div class="input-group">
                    {% csrf_token %}
                    <input name="email" type="text" class="form-control" placeholder="Email your email...">
                    <span class="input-group-btn">
                        <button class="btn" type="submit"><i class="fa fa-envelope-o"></i></button>
                    </span>
                </div>
            </div>
        </form>
    </div><!--/end container-->
</div>

mezzanine_tools/newsletter/templates/newsletter/register.html
{% extends 'base.html' %}
{% load i18n %}

{% block main %}

  <span>
  {{ msg }}
  </span>
  <a href="{% url 'home' %}">{% trans 'Back to main page' %}</a>
{% endblock main %}

mezzanine_tools/newsletter/templates/newsletter/registration_complete.html
{% extends 'base.html' %}
{% load i18n %}

{% block main %}

  <span>
    {% blocktrans with newsletter=newsletter %}You have successfully registered your email address {{ newsletter.email }} for the newsletter delivery.
    {% endblocktrans %}
  </span>
  <a href="{% url 'home' %}">{% trans 'Back to main page' %}</a>
{% endblock main %}

mezzanine_tools/newsletter/templates/newsletter/unregistration_complete.html
{% extends 'base.html' %}
{% load i18n %}

{% block main %}

  <span>
    {% blocktrans with newsletter=newsletter %}You have successfully unregistered your email address {{ newsletter.email }} from the newsletter delivery.
    {% endblocktrans %}
  </span>
  <a href="{% url 'home' %}">{% trans 'Back to main page' %}</a>
{% endblock main %}